- plugins/epic/data_source.py
> epic restful 替换

- plugins/statistics/statistics_handle.py
> fix GB18030 to UTF-8.

- plugins/bilibili_sub/data_source.py
- plugins/bilibili_sub/utils.py
弃用bilibili_api库，改用bilireq库，同时补充部分bilireq暂无的方法如：获取番剧、获取用户投稿视频
> 修改bilibili_sub插件在windows平台下报错

- plugins/word_clouds/__init__.py
- plugins/word_clouds/data_source.py
> Add word_clouds

- plugins/genshin/query_user/query_role/data_source.py
> fix: mihoyo bbs api changed

- poetry.lock
- pyproject.toml
> Update poetry file

- plugins/draw_card/handles/prts_handle.py
根据原项目的更新，修复了抽卡插件中方舟抽卡的问题。现在至少到能用的水平了，不会疯狂抽出卡提（？
能力有限，对于无法更新up池的问题还没有修复。
> 修复抽卡插件：方舟抽卡的抽取和显示问题

- basic_plugins/nickname.py
文案语法错误的修正：
- 从 “{NICKNAME}会好好记住的{msg}的，放心吧”
- 到 “{NICKNAME}会好好记住{msg}的，放心吧”
添加敏感词："父亲"。先前已有的敏感词 "爸", "爹", "爷"
> 修改nickname插件：一处文案错误，添加敏感词

- plugins/genshin/query_user/resin_remind/init_task.py
- plugins/gold_redbag/data_source.py
**发红包图片生成bug:**上一次的修复代码#688没有完全更新,这次补上
**原神树脂提醒报错:**发现add_job()多了参数,删除一个即可
> 上次修复的发红包图片生成bug;修复原神树脂提醒报错

- basic_plugins/super_cmd/bot_friend_group.py
- utils/image_utils.py
- utils/manager/requests_manager.py
> 稍微调整了一下查看所有请求中的年龄绘制

- plugins/gold_redbag/__init__.py
修复红包插件：当前一个红包过期时，新的人发红包会拿到前一个红包的余额 #750
> fix gold_redbag

- plugins/check_zhenxun_update/data_source.py
修复docker镜像中自动更新真寻的bug
原BUG在 https://github.com/SinKy-Yan/zhenxunbot-docker#%E5%B7%B2%E7%9F%A5%E9%97%AE%E9%A2%98
下面是修复之后的截图
> fix auto update bug

- plugins/check_zhenxun_update/__init__.py
> Windows 重启适配

- plugins/bilibili_sub/data_source.py
> 修复B站订阅UP动态

- plugins/epic/data_source.py
之前拼接规则局限性较大，比如这周的免费游戏《割草模拟器》/ Lawn Mowing Simulator 就无法处理。
> 更新 Epic 免费游戏商城链接拼接规则

- plugins/word_bank/_model.py
> fix: WordBank.check()

- plugins/word_bank/_model.py
- plugins/word_bank/_rule.py
fix https://github.com/HibiKier/zhenxun_bot/issues/1026
模糊匹配暂时也没找到相应方法，只能用sql语句。
> 修了下模糊匹配 issue#1026

- plugins/bt/data_source.py
> fix：bt url打开失败

- plugins/draw_card/handles/pretty_handle.py
> fix: 重载赛马娘卡池失败

- plugins/open_cases/__init__.py
> 修改重置开箱的使用权限

- plugins/draw_card/handles/ba_handle.py
学生档案获取换源：https://lonqie.github.io/SchaleDB/data/cn/students.min.json?v=49
> 修复碧蓝档案角色获取问题，换源

- plugins/fudu.py
> 把某人漏掉的给复制上去

- plugins/bilibili_sub/__init__.py
- plugins/bilibili_sub/data_source.py
- plugins/bilibili_sub/model.py
1、兼容B站下播的两种状态  [0, 2]
2、更改订阅入库逻辑，加入订阅类型
> fix: B站直播订阅的相关问题（issues 1158）

- basic_plugins/admin_bot_manage/rule.py
- basic_plugins/hooks/_utils.py
- basic_plugins/init_plugin_config/check_plugin_status.py
> fix switch_rule

- plugins/gold_redbag/__init__.py
> 解决开红包经常误触的问题

- basic_plugins/scripts.py
- basic_plugins/super_cmd/bot_friend_group.py
> 修复同意群聊请求以及添加群认证 更新变成查询的问题

- plugins/send_setu_/send_setu/__init__.py
- plugins/send_setu_/send_setu/data_source.py
1. 修复某些情况下会发出两张图片的问题
2. 限制色图连发图片数量
3. 连发正则新增指令
> 色图bug修复、增加指令

- basic_plugins/hooks/_utils.py
- basic_plugins/shop/gold.py
- plugins/russian/__init__.py
- utils/depends/__init__.py
> 修复bug: user_qq → user_id

- zhenxun/utils/browser.py
添加[镜像源](https://npmmirror.com/mirrors/playwright/)以加速 Playwright 下载
默认行为将读取zhenxun.configs.config中的SYSTEM_PROXY并添加镜像源进环境变量，下载结束后会使用restore_env_variables方法恢复环境变量
> :children_crossing: 更新 Chromium 安装逻辑, 添加 Playwright 依赖检查逻辑

- zhenxun/builtin_plugins/plugin_shop/config.py
> 更新 config.py

- zhenxun/builtin_plugins/plugin_store/__init__.py
- zhenxun/builtin_plugins/plugin_store/config.py
- zhenxun/builtin_plugins/plugin_store/data_source.py
添加了一个新的搜索命令，允许用户根据插件名称或作者搜索插件。
此外，更新了插件配置的URL列表，以使用新的API端点。
还修复了requirements.txt处理中的日志记录问题，并对插件安装和删除流程进行了微调。
添加了更新插件的功能，现在可以通过插件商店更新已安装的插件。此更新包括了插件版本的检查和更新逻辑，
优化了插件管理的便捷性。
> feat(plugin_store): 添加搜索插件功能和更新插件功能及更新配置URL

- zhenxun/builtin_plugins/web_ui/__init__.py
- zhenxun/builtin_plugins/web_ui/config.py
This reverts commit 65a6f608e677dd0a7f8fb1a057641cc5b7eb3a45.
> Revert "🐛 WebUI初始化逻辑修改 (#1574)"

- __version__
> :tada: chore(version): 自动更新版本到 v0.2.4-6359ba6

- __version__
> :tada: chore(version): 自动更新版本到 v0.2.4-b2da0a9

- __version__
> :tada: chore(version): 自动更新版本到 v0.2.4-e363d29

- zhenxun/builtin_plugins/web_ui/auth/__init__.py
> 🐞 fix(web_ui): 修复webui导入路径错误

- __version__
> :tada: chore(version): 自动更新版本到 v0.2.4-4291cda

- __version__
> :tada: chore(version): 自动更新版本到 v0.2.4-2c97eea

- zhenxun/builtin_plugins/web_ui/api/tabs/main/data_source.py
> :bug: 修复版本文件读取编码

- zhenxun/builtin_plugins/chat_history/chat_message_handle.py
- 新增用户头像显示
- 添加是否显示已退群用户的配置选项
- 优化移除退群用户后的排行数量显示
- 新增季消息排行选项
- 更新插件版本至0.2
> ✨ 增强消息统计功能

- zhenxun/builtin_plugins/statistics/statistics_hook.py
- resolve #1914
- resolve #1769
> 修复调用统计性能问题

- README.md
resolve[#1921](https://github.com/zhenxun-org/zhenxun_bot/issues/1921)
> 💬config文件路径描述修改

- zhenxun/utils/http_utils.py
> 增强 httpx 兼容性

- zhenxun/builtin_plugins/scheduler_admin/__init__.py
- zhenxun/builtin_plugins/scheduler_admin/command.py
- zhenxun/models/schedule_info.py
- zhenxun/services/db_context.py
- zhenxun/utils/manager/schedule_manager.py
**新增功能模块：**
1. **`schedule_manager.py`** - 通用定时任务管理器
- 提供插件级定时任务注册与管理机制
- 支持 cron、interval、date 三种触发器类型
- 实现任务的增删改查、暂停恢复、手动触发等完整生命周期管理
- 集成 APScheduler 实现高可靠性任务调度
- 支持群组级和全局级任务配置
2. **`schedule_info.py`** - 定时任务数据模型
- 定义任务持久化存储结构
- 支持 JSON 格式的触发器配置和任务参数
- 提供任务启用/禁用状态管理
3. **`scheduler_admin/`** - 定时任务管理命令插件
- 实现完整的命令行管理界面
- 支持任务查看、设置、删除、暂停、恢复、执行、更新等操作
- 提供分页显示和多维度筛选功能
- 集成权限控制和参数验证
**核心特性：**
- ✅ 插件装饰器注册机制，简化任务定义
- ✅ 数据库持久化，重启后自动恢复任务
- ✅ 灵活的参数传递和类型验证
- ✅ 群组级权限控制和任务隔离
- ✅ 可视化表格展示和状态监控
- ✅ 批量操作支持（全群设置/删除）
**适用场景：**
- 定时消息推送、数据同步、状态检查等周期性任务
- 插件开发者可通过简单装饰器快速集成定时功能
- 管理员可通过命令界面灵活管理所有定时任务
> ✨ feat!(scheduler): 引入通用持久化定时任务系统

- zhenxun/builtin_plugins/nickname.py
- 替换 on_regex 为 on_alconna，实现更灵活的命令解析
- 重构 CheckNickname 函数，改为异步函数并直接处理逻辑
- 更新昵称设置流程，提高代码可读性和维护性
- 优化消息回复逻辑，提升用户体验
- 优化昵称设置命令，防止误触发
> refactor(nickname): 使用 nonebot_plugin_alconna 重构昵称设置功能

- zhenxun/builtin_plugins/scheduler_admin/__init__.py
- zhenxun/builtin_plugins/scheduler_admin/command.py
- zhenxun/utils/manager/schedule_manager.py
- 新增状态查看、每日定时、私聊操作等功能
- 引入 Pydantic 参数验证，重构目标解析逻辑
- 添加并发控制，优化触发器显示格式
- 修复 ORM KeyError 问题，确保数据一致性
- 支持私聊通过 -g/-all 参数操作群组任务
> ✨ feat(scheduler): 增强定时任务管理系统

- zhenxun/builtin_plugins/help/__init__.py
- zhenxun/builtin_plugins/help/_data_source.py
- 【新功能】引入LLM智能帮助功能，当传统帮助未找到结果时，可自动调用LLM提供智能回复
- 【配置项】新增多项LLM帮助相关配置：
- `ENABLE_LLM_HELPER`: 控制LLM智能帮助的启用与禁用
- `DEFAULT_LLM_MODEL`: 配置智能帮助使用的LLM模型
- `LLM_HELPER_STYLE`: 设置LLM回复的口吻或风格
- `LLM_HELPER_REPLY_AS_IMAGE_THRESHOLD`: 定义LLM回复字数超过此阈值时转为图片发送
- 【逻辑优化】帮助指令处理流程调整：
- 优先尝试传统插件帮助查询
- 若传统查询无结果且LLM智能帮助已启用，则调用LLM进行自然语言回答
> ✨ feat(help): 引入LLM智能帮助并优化其功能

- __version__
> :tada: chore(version): 自动更新版本到 v0.2.4-da6d5b4

- zhenxun/builtin_plugins/scheduler_admin/handlers.py
- zhenxun/builtin_plugins/scheduler_admin/presenters.py
- zhenxun/models/scheduled_job.py
- zhenxun/services/scheduler/__init__.py
- zhenxun/services/scheduler/adapter.py
- zhenxun/services/scheduler/job.py
- zhenxun/services/scheduler/lifecycle.py
- zhenxun/services/scheduler/repository.py
- zhenxun/services/scheduler/service.py
- zhenxun/services/scheduler/targeter.py
- zhenxun/services/scheduler/triggers.py
- zhenxun/utils/decorator/retry.py
- 【模型重命名】将 `ScheduleInfo` 模型及其数据库表重命名为 `ScheduledJob`，以提高语义清晰度。
- 【触发器抽象】引入 `Trigger` 工厂类，提供类型安全的 Cron、Interval 和 Date 触发器配置。
- 【执行策略】新增 `ExecutionPolicy` 模型，允许为定时任务定义重试策略、延迟、异常类型以及成功/失败回调。
- 【任务执行】重构任务执行逻辑，支持 NoneBot 的依赖注入，并根据 `ExecutionPolicy` 处理任务的重试和回调。
- 【临时任务】增加声明式和编程式的临时任务调度能力，支持非持久化任务在运行时动态创建和执行。
- 【管理命令】更新定时任务管理命令 (`schedule_admin`)，使其适配新的 `ScheduledJob` 模型和参数验证逻辑。
- 【展示优化】改进定时任务列表和状态展示，使用新的触发器格式化逻辑和参数模型信息。
- 【重试装饰器】为 `Retry.api` 装饰器添加 `on_success` 回调，允许在任务成功执行后触发额外操作。
> ♻️ refactor(scheduler): 重构定时任务系统并增强功能

- zhenxun/builtin_plugins/plugin_store/data_source.py
- 将循环遍历的变量从 plugin_list 改为 all_plugin_list，以确保尝试更新所有插件
- 优化了插件更新日志的输出格式
> fix(zhenxun): 修正插件更新逻辑

- zhenxun/utils/http_utils.py
- 将 httpx.AsyncClient 实例化逻辑封装到 get_async_client 函数中
- 统一全局客户端和测试环境客户端的创建方式
- 提高代码复用性和可维护性
> fix(zhenxun): 修复 HTTP 客户端初始化逻辑错误

- requirements.txt
- 移除了大量不再需要的依赖项
- 更新了部分依赖项的版本，指定了版本范围
- 添加了少数新的依赖项
> build(deps): 更新项目依赖项

- zhenxun/builtin_plugins/check/__init__.py
- zhenxun/builtin_plugins/check/data_source.py
- 将插件版本从0.1更新至0.2
- 新增安全获取ARM设备CPU频率的函数get_arm_cpu_freq_safe
- 优化CPU信息采集逻辑，提高在ARM架构下的兼容性
> 🚑 fix(check): 修复自检插件在ARM设备下的CPU频率获取逻辑
